### ISSUE TITLE
hacker

### ISSUE THREAD

**Issue by imqxod** [meoawjidevfz/Flexer#1]
not rat ❌ 
https://skidware.dev/ is sigma ✅ 
mr cxdzy begging on tutorial how to get offsets ✅ 
"full stack dev" ❌ 
please kill yourself already nn

**Comment by meoawjidevfz** [comment]
> not rat ❌ https://skidware.dev/ is sigma ✅ mr cxdzy begging on tutorial how to get offsets ✅ "full stack dev" ❌ please kill yourself already nn

**Comment by imqxod** [comment]
well well well, nice close wannabe fullstack developer
